apiVersion: github.com/krancour/brignext/v2
kind: Project
metadata:
  id: secrets-demo
spec:
  description: A project that demonstrates the use of secrets
  worker:
    defaultConfigFiles:
      brignext.js: |-
        const { events, Job, Group, Container} = require("brigadier");

        events.on("github.com/krancour/brignext/cli:exec", (e) => {
          let fooJob = new Job("foo", "debian:latest", ["echo $FOO"]);
          fooJob.primaryContainer.env = {
            "FOO": e.project.secrets.FOO
          };
          
          fooJob.run()
          .then(result => {
            console.log("done");
          }).catch(e => {
            console.error(e);
          });
        });
