apiVersion: github.com/krancour/brignext/v2
kind: Project
metadata:
  id: sidecar-demo
spec:
  description: A project that demonstrates a job that uses a sidecar container
  worker:
    defaultConfigFiles:
      brignext.js: |-
        const { events, Job, Group, Container} = require("brigadier");

        events.on("github.com/krancour/brignext/cli:exec", (e) => {
          let fooJob = new Job("foo", "debian:latest", ["echo foo"]);
          fooJob.sidecarContainers = [
            new Container("sidecar", "debian:latest", ["sleep 10000"])
          ];

          fooJob.run()
          .then(() => {
            console.log("done");
          }).catch(e => {
            console.error(e);
          });
        });
