apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brignext.scheduler.fullname" . }}
  labels:
    {{- include "brignext.labels" . | nindent 4 }}
    {{- include "brignext.scheduler.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "brignext.selectorLabels" . | nindent 6 }}
      {{- include "brignext.scheduler.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "brignext.selectorLabels" . | nindent 8 }}
        {{- include "brignext.scheduler.labels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/scheduler/secret.yaml") . | sha256sum }}
    spec:
      serviceAccount: {{ include "brignext.scheduler.fullname" . }}
      containers:
      - name: scheduler
        image: {{ .Values.scheduler.image.repository }}:{{ default .Chart.AppVersion .Values.scheduler.image.tag }}
        imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
        args:
        - --logtostderr=true
        env:
        - name: API_ADDRESS
          {{- if .Values.apiserver.tls.enabled }}
          value: https://{{ include "brignext.apiserver.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          {{- else }}
          value: http://{{ include "brignext.apiserver.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          {{- end }}
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "brignext.scheduler.fullname" . }}
              key: api-token
        - name: IGNORE_API_CERT_WARNINGS
          value: {{ quote (and .Values.apiserver.tls.enabled .Values.scheduler.tls.ignoreCertWarnings) }}
        - name: DEFAULT_WORKER_IMAGE
          value: {{ .Values.worker.image.repository }}:{{ default .Chart.AppVersion .Values.worker.image.tag }}
        - name: DEFAULT_WORKER_IMAGE_PULL_POLICY
          value: {{ .Values.worker.image.pullPolicy }}
        - name: WORKSPACE_STORAGE_CLASS
          value: {{ .Values.scheduler.workspaceStorageClass }}
        {{- if eq .Values.messageBus "IncludedArtemis" }}
        - name: AMQP_ADDRESS
          value: amqp://{{ include "brignext.artemis.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5672
        - name: AMQP_USERNAME
          value: {{ .Values.artemis.username }}
        {{- else if eq .Values.messageBus "ExternalAMQP" }}
        - name: AMQP_ADDRESS
          value: {{ .Values.externalAMQP.address }}
        - name: AMQP_USERNAME
          value: {{ .Values.externalAMQP.username }}
        {{- else if eq .Values.messageBus "AzureServiceBus" }}
        - name: AMQP_ADDRESS
          value: {{ .Values.azureServiceBus.address }}
        - name: AMQP_USERNAME
          value: {{ .Values.azureServiceBus.username }}
        - name: AMQP_IS_AZURE_SERVICE_BUS
          value: "true"
        {{- end }}
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "brignext.scheduler.fullname" . }}
              key: amqp-password
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
