apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brignext.scheduler.fullname" . }}
  labels:
    {{- include "brignext.labels" . | nindent 4 }}
    {{- include "brignext.scheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ randAlphaNum 30 }}
  {{- if eq .Values.messageBus "IncludedArtemis" }}
  amqp-password: {{ .Values.artemis.password }}
  {{- else if eq .Values.messageBus "ExternalAMQP" }}
  amqp-password: {{ .Values.externalAMQP.password }}
  {{- else if eq .Values.messageBus "AzureServiceBus" }}
  amqp-password: {{ .Values.azureServiceBus.password }}
  {{- end }}
