{{- if eq .Values.messageBus "IncludedArtemis" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "brignext.artemis.fullname" . }}
  labels:
    {{- include "brignext.labels" . | nindent 4 }}
    {{- include "brignext.artemis.labels" . | nindent 4 }}
  {{- if .Values.artemis.ha.enabled }}
  annotations:
    # Exclude unready secondary nodes from DNS
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "false"
  {{- end }}
spec:
  type: {{ .Values.artemis.service.type }}
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    {{- include "brignext.selectorLabels" . | nindent 8 }}
    {{- include "brignext.artemis.labels" . | nindent 8 }}
{{- end }}
