// Code generated by protoc-gen-go. DO NOT EDIT.
// source: builds.proto

package builds

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBuildRequest struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBuildRequest) Reset()         { *m = CreateBuildRequest{} }
func (m *CreateBuildRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBuildRequest) ProtoMessage()    {}
func (*CreateBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{0}
}

func (m *CreateBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBuildRequest.Unmarshal(m, b)
}
func (m *CreateBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBuildRequest.Marshal(b, m, deterministic)
}
func (m *CreateBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBuildRequest.Merge(m, src)
}
func (m *CreateBuildRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBuildRequest.Size(m)
}
func (m *CreateBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBuildRequest proto.InternalMessageInfo

func (m *CreateBuildRequest) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

type CreateBuildResponse struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBuildResponse) Reset()         { *m = CreateBuildResponse{} }
func (m *CreateBuildResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBuildResponse) ProtoMessage()    {}
func (*CreateBuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{1}
}

func (m *CreateBuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBuildResponse.Unmarshal(m, b)
}
func (m *CreateBuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBuildResponse.Marshal(b, m, deterministic)
}
func (m *CreateBuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBuildResponse.Merge(m, src)
}
func (m *CreateBuildResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBuildResponse.Size(m)
}
func (m *CreateBuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBuildResponse proto.InternalMessageInfo

func (m *CreateBuildResponse) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

type GetBuildsRequest struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildsRequest) Reset()         { *m = GetBuildsRequest{} }
func (m *GetBuildsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBuildsRequest) ProtoMessage()    {}
func (*GetBuildsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{2}
}

func (m *GetBuildsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildsRequest.Unmarshal(m, b)
}
func (m *GetBuildsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildsRequest.Marshal(b, m, deterministic)
}
func (m *GetBuildsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildsRequest.Merge(m, src)
}
func (m *GetBuildsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBuildsRequest.Size(m)
}
func (m *GetBuildsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildsRequest proto.InternalMessageInfo

func (m *GetBuildsRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type GetBuildsResponse struct {
	Builds               []*Build `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildsResponse) Reset()         { *m = GetBuildsResponse{} }
func (m *GetBuildsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBuildsResponse) ProtoMessage()    {}
func (*GetBuildsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{3}
}

func (m *GetBuildsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildsResponse.Unmarshal(m, b)
}
func (m *GetBuildsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildsResponse.Marshal(b, m, deterministic)
}
func (m *GetBuildsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildsResponse.Merge(m, src)
}
func (m *GetBuildsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBuildsResponse.Size(m)
}
func (m *GetBuildsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildsResponse proto.InternalMessageInfo

func (m *GetBuildsResponse) GetBuilds() []*Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

type GetBuildRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildRequest) Reset()         { *m = GetBuildRequest{} }
func (m *GetBuildRequest) String() string { return proto.CompactTextString(m) }
func (*GetBuildRequest) ProtoMessage()    {}
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{4}
}

func (m *GetBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildRequest.Unmarshal(m, b)
}
func (m *GetBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildRequest.Marshal(b, m, deterministic)
}
func (m *GetBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildRequest.Merge(m, src)
}
func (m *GetBuildRequest) XXX_Size() int {
	return xxx_messageInfo_GetBuildRequest.Size(m)
}
func (m *GetBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildRequest proto.InternalMessageInfo

func (m *GetBuildRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBuildResponse struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildResponse) Reset()         { *m = GetBuildResponse{} }
func (m *GetBuildResponse) String() string { return proto.CompactTextString(m) }
func (*GetBuildResponse) ProtoMessage()    {}
func (*GetBuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{5}
}

func (m *GetBuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildResponse.Unmarshal(m, b)
}
func (m *GetBuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildResponse.Marshal(b, m, deterministic)
}
func (m *GetBuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildResponse.Merge(m, src)
}
func (m *GetBuildResponse) XXX_Size() int {
	return xxx_messageInfo_GetBuildResponse.Size(m)
}
func (m *GetBuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildResponse proto.InternalMessageInfo

func (m *GetBuildResponse) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

type DeleteBuildRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force                bool     `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBuildRequest) Reset()         { *m = DeleteBuildRequest{} }
func (m *DeleteBuildRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBuildRequest) ProtoMessage()    {}
func (*DeleteBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{6}
}

func (m *DeleteBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBuildRequest.Unmarshal(m, b)
}
func (m *DeleteBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBuildRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBuildRequest.Merge(m, src)
}
func (m *DeleteBuildRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBuildRequest.Size(m)
}
func (m *DeleteBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBuildRequest proto.InternalMessageInfo

func (m *DeleteBuildRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteBuildRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type DeleteBuildResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBuildResponse) Reset()         { *m = DeleteBuildResponse{} }
func (m *DeleteBuildResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBuildResponse) ProtoMessage()    {}
func (*DeleteBuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{7}
}

func (m *DeleteBuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBuildResponse.Unmarshal(m, b)
}
func (m *DeleteBuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBuildResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBuildResponse.Merge(m, src)
}
func (m *DeleteBuildResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBuildResponse.Size(m)
}
func (m *DeleteBuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBuildResponse proto.InternalMessageInfo

type DeleteAllBuildsRequest struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	Force                bool     `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllBuildsRequest) Reset()         { *m = DeleteAllBuildsRequest{} }
func (m *DeleteAllBuildsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllBuildsRequest) ProtoMessage()    {}
func (*DeleteAllBuildsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{8}
}

func (m *DeleteAllBuildsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllBuildsRequest.Unmarshal(m, b)
}
func (m *DeleteAllBuildsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllBuildsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllBuildsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllBuildsRequest.Merge(m, src)
}
func (m *DeleteAllBuildsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllBuildsRequest.Size(m)
}
func (m *DeleteAllBuildsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllBuildsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllBuildsRequest proto.InternalMessageInfo

func (m *DeleteAllBuildsRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *DeleteAllBuildsRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type DeleteAllBuildsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllBuildsResponse) Reset()         { *m = DeleteAllBuildsResponse{} }
func (m *DeleteAllBuildsResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllBuildsResponse) ProtoMessage()    {}
func (*DeleteAllBuildsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{9}
}

func (m *DeleteAllBuildsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllBuildsResponse.Unmarshal(m, b)
}
func (m *DeleteAllBuildsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllBuildsResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllBuildsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllBuildsResponse.Merge(m, src)
}
func (m *DeleteAllBuildsResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllBuildsResponse.Size(m)
}
func (m *DeleteAllBuildsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllBuildsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllBuildsResponse proto.InternalMessageInfo

type StreamBuildLogsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamBuildLogsRequest) Reset()         { *m = StreamBuildLogsRequest{} }
func (m *StreamBuildLogsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamBuildLogsRequest) ProtoMessage()    {}
func (*StreamBuildLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{10}
}

func (m *StreamBuildLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamBuildLogsRequest.Unmarshal(m, b)
}
func (m *StreamBuildLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamBuildLogsRequest.Marshal(b, m, deterministic)
}
func (m *StreamBuildLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamBuildLogsRequest.Merge(m, src)
}
func (m *StreamBuildLogsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamBuildLogsRequest.Size(m)
}
func (m *StreamBuildLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamBuildLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamBuildLogsRequest proto.InternalMessageInfo

func (m *StreamBuildLogsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Build struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectName          string    `protobuf:"bytes,2,opt,name=projectName,proto3" json:"projectName,omitempty"`
	Type                 string    `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Provider             string    `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	ShortTitle           string    `protobuf:"bytes,5,opt,name=shortTitle,proto3" json:"shortTitle,omitempty"`
	LongTitle            string    `protobuf:"bytes,6,opt,name=longTitle,proto3" json:"longTitle,omitempty"`
	CloneURL             string    `protobuf:"bytes,7,opt,name=cloneURL,proto3" json:"cloneURL,omitempty"`
	Revision             *Revision `protobuf:"bytes,8,opt,name=revision,proto3" json:"revision,omitempty"`
	Payload              []byte    `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	Script               []byte    `protobuf:"bytes,10,opt,name=script,proto3" json:"script,omitempty"`
	Config               []byte    `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"`
	Worker               *Worker   `protobuf:"bytes,12,opt,name=worker,proto3" json:"worker,omitempty"`
	LogLevel             string    `protobuf:"bytes,13,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{11}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Build) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *Build) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Build) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Build) GetShortTitle() string {
	if m != nil {
		return m.ShortTitle
	}
	return ""
}

func (m *Build) GetLongTitle() string {
	if m != nil {
		return m.LongTitle
	}
	return ""
}

func (m *Build) GetCloneURL() string {
	if m != nil {
		return m.CloneURL
	}
	return ""
}

func (m *Build) GetRevision() *Revision {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *Build) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Build) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *Build) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Build) GetWorker() *Worker {
	if m != nil {
		return m.Worker
	}
	return nil
}

func (m *Build) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

type Revision struct {
	Commit               string   `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Revision) Reset()         { *m = Revision{} }
func (m *Revision) String() string { return proto.CompactTextString(m) }
func (*Revision) ProtoMessage()    {}
func (*Revision) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{12}
}

func (m *Revision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Revision.Unmarshal(m, b)
}
func (m *Revision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Revision.Marshal(b, m, deterministic)
}
func (m *Revision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Revision.Merge(m, src)
}
func (m *Revision) XXX_Size() int {
	return xxx_messageInfo_Revision.Size(m)
}
func (m *Revision) XXX_DiscardUnknown() {
	xxx_messageInfo_Revision.DiscardUnknown(m)
}

var xxx_messageInfo_Revision proto.InternalMessageInfo

func (m *Revision) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *Revision) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type Worker struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildID              string   `protobuf:"bytes,2,opt,name=buildID,proto3" json:"buildID,omitempty"`
	ProjectID            string   `protobuf:"bytes,3,opt,name=projectID,proto3" json:"projectID,omitempty"`
	StartTime            int64    `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64    `protobuf:"varint,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	ExitCode             int32    `protobuf:"varint,6,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Worker) Reset()         { *m = Worker{} }
func (m *Worker) String() string { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()    {}
func (*Worker) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{13}
}

func (m *Worker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Worker.Unmarshal(m, b)
}
func (m *Worker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Worker.Marshal(b, m, deterministic)
}
func (m *Worker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Worker.Merge(m, src)
}
func (m *Worker) XXX_Size() int {
	return xxx_messageInfo_Worker.Size(m)
}
func (m *Worker) XXX_DiscardUnknown() {
	xxx_messageInfo_Worker.DiscardUnknown(m)
}

var xxx_messageInfo_Worker proto.InternalMessageInfo

func (m *Worker) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Worker) GetBuildID() string {
	if m != nil {
		return m.BuildID
	}
	return ""
}

func (m *Worker) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

func (m *Worker) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Worker) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Worker) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *Worker) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type LogEntry struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b027489ada71b728, []int{14}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogEntry) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateBuildRequest)(nil), "builds.CreateBuildRequest")
	proto.RegisterType((*CreateBuildResponse)(nil), "builds.CreateBuildResponse")
	proto.RegisterType((*GetBuildsRequest)(nil), "builds.GetBuildsRequest")
	proto.RegisterType((*GetBuildsResponse)(nil), "builds.GetBuildsResponse")
	proto.RegisterType((*GetBuildRequest)(nil), "builds.GetBuildRequest")
	proto.RegisterType((*GetBuildResponse)(nil), "builds.GetBuildResponse")
	proto.RegisterType((*DeleteBuildRequest)(nil), "builds.DeleteBuildRequest")
	proto.RegisterType((*DeleteBuildResponse)(nil), "builds.DeleteBuildResponse")
	proto.RegisterType((*DeleteAllBuildsRequest)(nil), "builds.DeleteAllBuildsRequest")
	proto.RegisterType((*DeleteAllBuildsResponse)(nil), "builds.DeleteAllBuildsResponse")
	proto.RegisterType((*StreamBuildLogsRequest)(nil), "builds.StreamBuildLogsRequest")
	proto.RegisterType((*Build)(nil), "builds.Build")
	proto.RegisterType((*Revision)(nil), "builds.Revision")
	proto.RegisterType((*Worker)(nil), "builds.Worker")
	proto.RegisterType((*LogEntry)(nil), "builds.LogEntry")
}

func init() { proto.RegisterFile("builds.proto", fileDescriptor_b027489ada71b728) }

var fileDescriptor_b027489ada71b728 = []byte{
	// 700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5d, 0x6f, 0xd3, 0x4a,
	0x10, 0xad, 0x93, 0x26, 0x4d, 0x26, 0xfd, 0xba, 0xdb, 0x7b, 0xdb, 0x6d, 0x2e, 0x2a, 0xc1, 0x08,
	0x94, 0x07, 0x14, 0x50, 0xa9, 0x04, 0xf4, 0x05, 0x91, 0x16, 0xb5, 0x95, 0x22, 0x54, 0x99, 0x22,
	0x9e, 0xdd, 0x78, 0x1a, 0x16, 0x1c, 0xaf, 0xd9, 0xdd, 0x96, 0xf6, 0xbf, 0xf1, 0xc0, 0x3f, 0x03,
	0x79, 0x3f, 0xec, 0xd4, 0x4e, 0x25, 0xfa, 0xe6, 0x73, 0xce, 0xce, 0x9c, 0x99, 0x9d, 0xcd, 0x04,
	0x96, 0xcf, 0x2f, 0x59, 0x1c, 0xc9, 0x41, 0x2a, 0xb8, 0xe2, 0xa4, 0x69, 0x90, 0xff, 0x06, 0xc8,
	0x81, 0xc0, 0x50, 0xe1, 0x30, 0xc3, 0x01, 0x7e, 0xbf, 0x44, 0xa9, 0xc8, 0x63, 0x68, 0x68, 0x9d,
	0x7a, 0x3d, 0xaf, 0xdf, 0xd9, 0x5d, 0x19, 0xd8, 0x58, 0x73, 0xc8, 0x68, 0xfe, 0x3e, 0x6c, 0xdc,
	0x0a, 0x95, 0x29, 0x4f, 0x24, 0xfe, 0x5d, 0xec, 0x1e, 0xac, 0x1f, 0xa1, 0xd2, 0x94, 0x74, 0xa6,
	0x3d, 0xe8, 0xa4, 0x82, 0x7f, 0xc5, 0xb1, 0xfa, 0x10, 0x4e, 0x51, 0x87, 0xb7, 0x83, 0x59, 0xca,
	0xdf, 0x87, 0x7f, 0x66, 0xa2, 0xac, 0xdf, 0x13, 0xb0, 0xbd, 0x50, 0xaf, 0x57, 0xaf, 0x1a, 0xba,
	0x46, 0x1f, 0xc1, 0x9a, 0x8b, 0x75, 0x86, 0xab, 0x50, 0x63, 0x91, 0xf5, 0xa9, 0xb1, 0xc8, 0x7f,
	0x55, 0x14, 0x75, 0xbf, 0x6e, 0xf6, 0x81, 0x1c, 0x62, 0x8c, 0xa5, 0x4b, 0x2c, 0xa5, 0x27, 0xff,
	0x42, 0xe3, 0x82, 0x8b, 0x31, 0xd2, 0x5a, 0xcf, 0xeb, 0xb7, 0x02, 0x03, 0xfc, 0xff, 0x60, 0xe3,
	0x56, 0xac, 0xf1, 0xf5, 0x4f, 0x61, 0xd3, 0xd0, 0xef, 0xe2, 0xf8, 0x9e, 0xd7, 0x74, 0x87, 0xd1,
	0x36, 0x6c, 0x55, 0x32, 0x5a, 0xb3, 0x3e, 0x6c, 0x7e, 0x54, 0x02, 0xc3, 0xa9, 0xe6, 0x47, 0x7c,
	0x22, 0xef, 0xba, 0xa2, 0xdf, 0x35, 0x68, 0xe8, 0x43, 0x95, 0xee, 0x4a, 0x65, 0xd5, 0xaa, 0x65,
	0x11, 0x58, 0x54, 0x37, 0x29, 0xd2, 0xba, 0x96, 0xf4, 0x37, 0xe9, 0x42, 0x2b, 0x15, 0xfc, 0x8a,
	0x45, 0x28, 0xe8, 0xa2, 0xe6, 0x73, 0x4c, 0x76, 0x00, 0xe4, 0x17, 0x2e, 0xd4, 0x19, 0x53, 0x31,
	0xd2, 0x86, 0x56, 0x67, 0x18, 0xf2, 0x00, 0xda, 0x31, 0x4f, 0x26, 0x46, 0x6e, 0x6a, 0xb9, 0x20,
	0xb2, 0xcc, 0xe3, 0x98, 0x27, 0xf8, 0x29, 0x18, 0xd1, 0x25, 0x93, 0xd9, 0x61, 0xf2, 0x0c, 0x5a,
	0x02, 0xaf, 0x98, 0x64, 0x3c, 0xa1, 0x2d, 0x3d, 0xd7, 0x75, 0x37, 0xd7, 0xc0, 0xf2, 0x41, 0x7e,
	0x82, 0x50, 0x58, 0x4a, 0xc3, 0x9b, 0x98, 0x87, 0x11, 0x6d, 0xf7, 0xbc, 0xfe, 0x72, 0xe0, 0x20,
	0xd9, 0x84, 0xa6, 0x1c, 0x0b, 0x96, 0x2a, 0x0a, 0x5a, 0xb0, 0x28, 0xe3, 0xc7, 0x3c, 0xb9, 0x60,
	0x13, 0xda, 0x31, 0xbc, 0x41, 0xe4, 0x29, 0x34, 0x7f, 0x70, 0xf1, 0x0d, 0x05, 0x5d, 0xd6, 0xae,
	0xab, 0xce, 0xf5, 0xb3, 0x66, 0x03, 0xab, 0x66, 0xb5, 0xc7, 0x7c, 0x32, 0xc2, 0x2b, 0x8c, 0xe9,
	0x8a, 0xa9, 0xdd, 0x61, 0x7f, 0x0f, 0x5a, 0xae, 0x46, 0xe3, 0x33, 0x9d, 0x32, 0x65, 0xe7, 0x60,
	0x11, 0x59, 0x87, 0xba, 0xc0, 0x0b, 0x3b, 0x83, 0xec, 0xd3, 0xff, 0xe9, 0x41, 0xd3, 0x98, 0x54,
	0x06, 0x47, 0x61, 0x49, 0x57, 0x71, 0x72, 0x68, 0x03, 0x1c, 0xcc, 0x2e, 0xd8, 0xce, 0xef, 0xe4,
	0xd0, 0x4e, 0xad, 0x20, 0x32, 0x55, 0xaa, 0x30, 0x1b, 0xc6, 0x14, 0xf5, 0xec, 0xea, 0x41, 0x41,
	0x64, 0x59, 0x31, 0x89, 0xb4, 0xd6, 0xd0, 0x9a, 0x83, 0x59, 0x73, 0x78, 0xcd, 0xd4, 0x01, 0x8f,
	0xcc, 0xd4, 0x1a, 0x41, 0x8e, 0xf5, 0x85, 0xaa, 0x50, 0x5d, 0x4a, 0x3b, 0x32, 0x8b, 0xfc, 0xd7,
	0xd0, 0x1a, 0xf1, 0xc9, 0xfb, 0x44, 0x89, 0x1b, 0xfd, 0x8c, 0x98, 0x7d, 0xf8, 0xf5, 0x40, 0x7f,
	0x67, 0x6e, 0x53, 0x94, 0x32, 0x9c, 0xb8, 0x87, 0xe7, 0xe0, 0xee, 0xaf, 0x3a, 0x34, 0xcd, 0x6b,
	0x27, 0xc7, 0xd0, 0x99, 0xd9, 0x57, 0xa4, 0xeb, 0x2e, 0xbf, 0xba, 0xff, 0xba, 0xff, 0xcf, 0xd5,
	0xec, 0xaf, 0x65, 0x81, 0x0c, 0xa1, 0x9d, 0xef, 0x21, 0x42, 0xdd, 0xd9, 0xf2, 0x42, 0xeb, 0x6e,
	0xcf, 0x51, 0xf2, 0x1c, 0x6f, 0xa1, 0xe5, 0x68, 0xb2, 0x55, 0x3e, 0xe8, 0x32, 0xd0, 0xaa, 0x90,
	0x27, 0x38, 0x86, 0xce, 0xcc, 0xe2, 0x28, 0xda, 0xa9, 0x6e, 0xa2, 0xa2, 0x9d, 0x79, 0x9b, 0x66,
	0x81, 0x9c, 0xc1, 0x5a, 0x69, 0x33, 0x90, 0x9d, 0xdb, 0x11, 0xe5, 0x25, 0xd4, 0x7d, 0x78, 0xa7,
	0x9e, 0x67, 0x3d, 0x82, 0xb5, 0xd2, 0x52, 0x29, 0xb2, 0xce, 0xdf, 0x36, 0xdd, 0xfc, 0x57, 0xe8,
	0x86, 0xed, 0x2f, 0xbc, 0xf0, 0x86, 0xcf, 0xa1, 0xc7, 0xf8, 0x20, 0x42, 0x26, 0xe3, 0xf0, 0x5c,
	0x0e, 0xb8, 0x64, 0x82, 0xc9, 0x01, 0x5e, 0x87, 0xd3, 0x34, 0x46, 0x39, 0x88, 0xf9, 0x44, 0x0e,
	0xdb, 0x59, 0x9a, 0xd3, 0xec, 0x9f, 0xed, 0xd4, 0x3b, 0x6f, 0xea, 0xbf, 0xb8, 0x97, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xcc, 0xba, 0xd4, 0x7a, 0xf2, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuildsClient is the client API for Builds service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuildsClient interface {
	CreateBuild(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*CreateBuildResponse, error)
	GetBuilds(ctx context.Context, in *GetBuildsRequest, opts ...grpc.CallOption) (*GetBuildsResponse, error)
	GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*GetBuildResponse, error)
	DeleteBuild(ctx context.Context, in *DeleteBuildRequest, opts ...grpc.CallOption) (*DeleteBuildResponse, error)
	DeleteAllBuilds(ctx context.Context, in *DeleteAllBuildsRequest, opts ...grpc.CallOption) (*DeleteAllBuildsResponse, error)
	StreamBuildLogs(ctx context.Context, in *StreamBuildLogsRequest, opts ...grpc.CallOption) (Builds_StreamBuildLogsClient, error)
}

type buildsClient struct {
	cc *grpc.ClientConn
}

func NewBuildsClient(cc *grpc.ClientConn) BuildsClient {
	return &buildsClient{cc}
}

func (c *buildsClient) CreateBuild(ctx context.Context, in *CreateBuildRequest, opts ...grpc.CallOption) (*CreateBuildResponse, error) {
	out := new(CreateBuildResponse)
	err := c.cc.Invoke(ctx, "/builds.Builds/CreateBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildsClient) GetBuilds(ctx context.Context, in *GetBuildsRequest, opts ...grpc.CallOption) (*GetBuildsResponse, error) {
	out := new(GetBuildsResponse)
	err := c.cc.Invoke(ctx, "/builds.Builds/GetBuilds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildsClient) GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*GetBuildResponse, error) {
	out := new(GetBuildResponse)
	err := c.cc.Invoke(ctx, "/builds.Builds/GetBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildsClient) DeleteBuild(ctx context.Context, in *DeleteBuildRequest, opts ...grpc.CallOption) (*DeleteBuildResponse, error) {
	out := new(DeleteBuildResponse)
	err := c.cc.Invoke(ctx, "/builds.Builds/DeleteBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildsClient) DeleteAllBuilds(ctx context.Context, in *DeleteAllBuildsRequest, opts ...grpc.CallOption) (*DeleteAllBuildsResponse, error) {
	out := new(DeleteAllBuildsResponse)
	err := c.cc.Invoke(ctx, "/builds.Builds/DeleteAllBuilds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildsClient) StreamBuildLogs(ctx context.Context, in *StreamBuildLogsRequest, opts ...grpc.CallOption) (Builds_StreamBuildLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Builds_serviceDesc.Streams[0], "/builds.Builds/StreamBuildLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &buildsStreamBuildLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Builds_StreamBuildLogsClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type buildsStreamBuildLogsClient struct {
	grpc.ClientStream
}

func (x *buildsStreamBuildLogsClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BuildsServer is the server API for Builds service.
type BuildsServer interface {
	CreateBuild(context.Context, *CreateBuildRequest) (*CreateBuildResponse, error)
	GetBuilds(context.Context, *GetBuildsRequest) (*GetBuildsResponse, error)
	GetBuild(context.Context, *GetBuildRequest) (*GetBuildResponse, error)
	DeleteBuild(context.Context, *DeleteBuildRequest) (*DeleteBuildResponse, error)
	DeleteAllBuilds(context.Context, *DeleteAllBuildsRequest) (*DeleteAllBuildsResponse, error)
	StreamBuildLogs(*StreamBuildLogsRequest, Builds_StreamBuildLogsServer) error
}

func RegisterBuildsServer(s *grpc.Server, srv BuildsServer) {
	s.RegisterService(&_Builds_serviceDesc, srv)
}

func _Builds_CreateBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildsServer).CreateBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/builds.Builds/CreateBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildsServer).CreateBuild(ctx, req.(*CreateBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builds_GetBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildsServer).GetBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/builds.Builds/GetBuilds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildsServer).GetBuilds(ctx, req.(*GetBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builds_GetBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildsServer).GetBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/builds.Builds/GetBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildsServer).GetBuild(ctx, req.(*GetBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builds_DeleteBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildsServer).DeleteBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/builds.Builds/DeleteBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildsServer).DeleteBuild(ctx, req.(*DeleteBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builds_DeleteAllBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildsServer).DeleteAllBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/builds.Builds/DeleteAllBuilds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildsServer).DeleteAllBuilds(ctx, req.(*DeleteAllBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Builds_StreamBuildLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBuildLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BuildsServer).StreamBuildLogs(m, &buildsStreamBuildLogsServer{stream})
}

type Builds_StreamBuildLogsServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type buildsStreamBuildLogsServer struct {
	grpc.ServerStream
}

func (x *buildsStreamBuildLogsServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

var _Builds_serviceDesc = grpc.ServiceDesc{
	ServiceName: "builds.Builds",
	HandlerType: (*BuildsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBuild",
			Handler:    _Builds_CreateBuild_Handler,
		},
		{
			MethodName: "GetBuilds",
			Handler:    _Builds_GetBuilds_Handler,
		},
		{
			MethodName: "GetBuild",
			Handler:    _Builds_GetBuild_Handler,
		},
		{
			MethodName: "DeleteBuild",
			Handler:    _Builds_DeleteBuild_Handler,
		},
		{
			MethodName: "DeleteAllBuilds",
			Handler:    _Builds_DeleteAllBuilds_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBuildLogs",
			Handler:       _Builds_StreamBuildLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "builds.proto",
}
