// Code generated by protoc-gen-go. DO NOT EDIT.
// source: projects.proto

package projects

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateProjectRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{0}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type CreateProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{1}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type GetProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectsRequest) Reset()         { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()    {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{2}
}

func (m *GetProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsRequest.Unmarshal(m, b)
}
func (m *GetProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsRequest.Merge(m, src)
}
func (m *GetProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectsRequest.Size(m)
}
func (m *GetProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsRequest proto.InternalMessageInfo

type GetProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProjectsResponse) Reset()         { *m = GetProjectsResponse{} }
func (m *GetProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectsResponse) ProtoMessage()    {}
func (*GetProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{3}
}

func (m *GetProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsResponse.Unmarshal(m, b)
}
func (m *GetProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsResponse.Merge(m, src)
}
func (m *GetProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectsResponse.Size(m)
}
func (m *GetProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsResponse proto.InternalMessageInfo

func (m *GetProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type GetProjectRequest struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectRequest) Reset()         { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()    {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{4}
}

func (m *GetProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRequest.Unmarshal(m, b)
}
func (m *GetProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRequest.Merge(m, src)
}
func (m *GetProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectRequest.Size(m)
}
func (m *GetProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRequest proto.InternalMessageInfo

func (m *GetProjectRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type GetProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectResponse) Reset()         { *m = GetProjectResponse{} }
func (m *GetProjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectResponse) ProtoMessage()    {}
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{5}
}

func (m *GetProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectResponse.Unmarshal(m, b)
}
func (m *GetProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectResponse.Merge(m, src)
}
func (m *GetProjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectResponse.Size(m)
}
func (m *GetProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectResponse proto.InternalMessageInfo

func (m *GetProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectRequest) Reset()         { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()    {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{6}
}

func (m *UpdateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectRequest.Unmarshal(m, b)
}
func (m *UpdateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectRequest.Merge(m, src)
}
func (m *UpdateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectRequest.Size(m)
}
func (m *UpdateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectRequest proto.InternalMessageInfo

func (m *UpdateProjectRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type UpdateProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectResponse) Reset()         { *m = UpdateProjectResponse{} }
func (m *UpdateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectResponse) ProtoMessage()    {}
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{7}
}

func (m *UpdateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectResponse.Unmarshal(m, b)
}
func (m *UpdateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectResponse.Merge(m, src)
}
func (m *UpdateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectResponse.Size(m)
}
func (m *UpdateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectResponse proto.InternalMessageInfo

func (m *UpdateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProjectRequest) Reset()         { *m = DeleteProjectRequest{} }
func (m *DeleteProjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProjectRequest) ProtoMessage()    {}
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{8}
}

func (m *DeleteProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectRequest.Unmarshal(m, b)
}
func (m *DeleteProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectRequest.Merge(m, src)
}
func (m *DeleteProjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectRequest.Size(m)
}
func (m *DeleteProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectRequest proto.InternalMessageInfo

func (m *DeleteProjectRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type DeleteProjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProjectResponse) Reset()         { *m = DeleteProjectResponse{} }
func (m *DeleteProjectResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProjectResponse) ProtoMessage()    {}
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{9}
}

func (m *DeleteProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectResponse.Unmarshal(m, b)
}
func (m *DeleteProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectResponse.Merge(m, src)
}
func (m *DeleteProjectResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectResponse.Size(m)
}
func (m *DeleteProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectResponse proto.InternalMessageInfo

type Project struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repo                 *Repo             `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	DefaultScript        string            `protobuf:"bytes,3,opt,name=defaultScript,proto3" json:"defaultScript,omitempty"`
	DefaultScriptName    string            `protobuf:"bytes,4,opt,name=defaultScriptName,proto3" json:"defaultScriptName,omitempty"`
	Kubernetes           *Kubernetes       `protobuf:"bytes,5,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	SharedSecret         string            `protobuf:"bytes,6,opt,name=sharedSecret,proto3" json:"sharedSecret,omitempty"`
	Github               *Github           `protobuf:"bytes,7,opt,name=github,proto3" json:"github,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,8,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Worker               *WorkerConfig     `protobuf:"bytes,9,opt,name=Worker,proto3" json:"Worker,omitempty"`
	InitGitSubmodules    bool              `protobuf:"varint,10,opt,name=initGitSubmodules,proto3" json:"initGitSubmodules,omitempty"`
	AllowPrivilegedJobs  bool              `protobuf:"varint,11,opt,name=allowPrivilegedJobs,proto3" json:"allowPrivilegedJobs,omitempty"`
	AllowHostMounts      bool              `protobuf:"varint,12,opt,name=allowHostMounts,proto3" json:"allowHostMounts,omitempty"`
	ImagePullSecrets     string            `protobuf:"bytes,13,opt,name=imagePullSecrets,proto3" json:"imagePullSecrets,omitempty"`
	WorkerCommand        string            `protobuf:"bytes,14,opt,name=workerCommand,proto3" json:"workerCommand,omitempty"`
	BrigadejsPath        string            `protobuf:"bytes,15,opt,name=BrigadejsPath,proto3" json:"BrigadejsPath,omitempty"`
	BrigadeConfigPath    string            `protobuf:"bytes,16,opt,name=BrigadeConfigPath,proto3" json:"BrigadeConfigPath,omitempty"`
	GenericGatewaySecret string            `protobuf:"bytes,17,opt,name=GenericGatewaySecret,proto3" json:"GenericGatewaySecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{10}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *Project) GetDefaultScript() string {
	if m != nil {
		return m.DefaultScript
	}
	return ""
}

func (m *Project) GetDefaultScriptName() string {
	if m != nil {
		return m.DefaultScriptName
	}
	return ""
}

func (m *Project) GetKubernetes() *Kubernetes {
	if m != nil {
		return m.Kubernetes
	}
	return nil
}

func (m *Project) GetSharedSecret() string {
	if m != nil {
		return m.SharedSecret
	}
	return ""
}

func (m *Project) GetGithub() *Github {
	if m != nil {
		return m.Github
	}
	return nil
}

func (m *Project) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *Project) GetWorker() *WorkerConfig {
	if m != nil {
		return m.Worker
	}
	return nil
}

func (m *Project) GetInitGitSubmodules() bool {
	if m != nil {
		return m.InitGitSubmodules
	}
	return false
}

func (m *Project) GetAllowPrivilegedJobs() bool {
	if m != nil {
		return m.AllowPrivilegedJobs
	}
	return false
}

func (m *Project) GetAllowHostMounts() bool {
	if m != nil {
		return m.AllowHostMounts
	}
	return false
}

func (m *Project) GetImagePullSecrets() string {
	if m != nil {
		return m.ImagePullSecrets
	}
	return ""
}

func (m *Project) GetWorkerCommand() string {
	if m != nil {
		return m.WorkerCommand
	}
	return ""
}

func (m *Project) GetBrigadejsPath() string {
	if m != nil {
		return m.BrigadejsPath
	}
	return ""
}

func (m *Project) GetBrigadeConfigPath() string {
	if m != nil {
		return m.BrigadeConfigPath
	}
	return ""
}

func (m *Project) GetGenericGatewaySecret() string {
	if m != nil {
		return m.GenericGatewaySecret
	}
	return ""
}

type Repo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CloneURL             string   `protobuf:"bytes,2,opt,name=cloneURL,proto3" json:"cloneURL,omitempty"`
	SshKey               string   `protobuf:"bytes,3,opt,name=sshKey,proto3" json:"sshKey,omitempty"`
	SshCert              string   `protobuf:"bytes,4,opt,name=sshCert,proto3" json:"sshCert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repo) Reset()         { *m = Repo{} }
func (m *Repo) String() string { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()    {}
func (*Repo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{11}
}

func (m *Repo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repo.Unmarshal(m, b)
}
func (m *Repo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repo.Marshal(b, m, deterministic)
}
func (m *Repo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repo.Merge(m, src)
}
func (m *Repo) XXX_Size() int {
	return xxx_messageInfo_Repo.Size(m)
}
func (m *Repo) XXX_DiscardUnknown() {
	xxx_messageInfo_Repo.DiscardUnknown(m)
}

var xxx_messageInfo_Repo proto.InternalMessageInfo

func (m *Repo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repo) GetCloneURL() string {
	if m != nil {
		return m.CloneURL
	}
	return ""
}

func (m *Repo) GetSshKey() string {
	if m != nil {
		return m.SshKey
	}
	return ""
}

func (m *Repo) GetSshCert() string {
	if m != nil {
		return m.SshCert
	}
	return ""
}

type Kubernetes struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	VcsSidecar           string   `protobuf:"bytes,2,opt,name=vcsSidecar,proto3" json:"vcsSidecar,omitempty"`
	BuildStorageSize     string   `protobuf:"bytes,3,opt,name=buildStorageSize,proto3" json:"buildStorageSize,omitempty"`
	BuildStorageClass    string   `protobuf:"bytes,4,opt,name=buildStorageClass,proto3" json:"buildStorageClass,omitempty"`
	CacheStorageClass    string   `protobuf:"bytes,5,opt,name=cacheStorageClass,proto3" json:"cacheStorageClass,omitempty"`
	AllowSecretKeyRef    bool     `protobuf:"varint,6,opt,name=allowSecretKeyRef,proto3" json:"allowSecretKeyRef,omitempty"`
	ServiceAccount       string   `protobuf:"bytes,7,opt,name=serviceAccount,proto3" json:"serviceAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Kubernetes) Reset()         { *m = Kubernetes{} }
func (m *Kubernetes) String() string { return proto.CompactTextString(m) }
func (*Kubernetes) ProtoMessage()    {}
func (*Kubernetes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{12}
}

func (m *Kubernetes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kubernetes.Unmarshal(m, b)
}
func (m *Kubernetes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kubernetes.Marshal(b, m, deterministic)
}
func (m *Kubernetes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kubernetes.Merge(m, src)
}
func (m *Kubernetes) XXX_Size() int {
	return xxx_messageInfo_Kubernetes.Size(m)
}
func (m *Kubernetes) XXX_DiscardUnknown() {
	xxx_messageInfo_Kubernetes.DiscardUnknown(m)
}

var xxx_messageInfo_Kubernetes proto.InternalMessageInfo

func (m *Kubernetes) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Kubernetes) GetVcsSidecar() string {
	if m != nil {
		return m.VcsSidecar
	}
	return ""
}

func (m *Kubernetes) GetBuildStorageSize() string {
	if m != nil {
		return m.BuildStorageSize
	}
	return ""
}

func (m *Kubernetes) GetBuildStorageClass() string {
	if m != nil {
		return m.BuildStorageClass
	}
	return ""
}

func (m *Kubernetes) GetCacheStorageClass() string {
	if m != nil {
		return m.CacheStorageClass
	}
	return ""
}

func (m *Kubernetes) GetAllowSecretKeyRef() bool {
	if m != nil {
		return m.AllowSecretKeyRef
	}
	return false
}

func (m *Kubernetes) GetServiceAccount() string {
	if m != nil {
		return m.ServiceAccount
	}
	return ""
}

type Github struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	BaseURL              string   `protobuf:"bytes,2,opt,name=baseURL,proto3" json:"baseURL,omitempty"`
	UploadURL            string   `protobuf:"bytes,3,opt,name=uploadURL,proto3" json:"uploadURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Github) Reset()         { *m = Github{} }
func (m *Github) String() string { return proto.CompactTextString(m) }
func (*Github) ProtoMessage()    {}
func (*Github) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{13}
}

func (m *Github) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Github.Unmarshal(m, b)
}
func (m *Github) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Github.Marshal(b, m, deterministic)
}
func (m *Github) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Github.Merge(m, src)
}
func (m *Github) XXX_Size() int {
	return xxx_messageInfo_Github.Size(m)
}
func (m *Github) XXX_DiscardUnknown() {
	xxx_messageInfo_Github.DiscardUnknown(m)
}

var xxx_messageInfo_Github proto.InternalMessageInfo

func (m *Github) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Github) GetBaseURL() string {
	if m != nil {
		return m.BaseURL
	}
	return ""
}

func (m *Github) GetUploadURL() string {
	if m != nil {
		return m.UploadURL
	}
	return ""
}

type WorkerConfig struct {
	Registry             string   `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	PullPolicy           string   `protobuf:"bytes,4,opt,name=pullPolicy,proto3" json:"pullPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerConfig) Reset()         { *m = WorkerConfig{} }
func (m *WorkerConfig) String() string { return proto.CompactTextString(m) }
func (*WorkerConfig) ProtoMessage()    {}
func (*WorkerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2826043bb82544a, []int{14}
}

func (m *WorkerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerConfig.Unmarshal(m, b)
}
func (m *WorkerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerConfig.Marshal(b, m, deterministic)
}
func (m *WorkerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerConfig.Merge(m, src)
}
func (m *WorkerConfig) XXX_Size() int {
	return xxx_messageInfo_WorkerConfig.Size(m)
}
func (m *WorkerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerConfig proto.InternalMessageInfo

func (m *WorkerConfig) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *WorkerConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkerConfig) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *WorkerConfig) GetPullPolicy() string {
	if m != nil {
		return m.PullPolicy
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateProjectRequest)(nil), "projects.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "projects.CreateProjectResponse")
	proto.RegisterType((*GetProjectsRequest)(nil), "projects.GetProjectsRequest")
	proto.RegisterType((*GetProjectsResponse)(nil), "projects.GetProjectsResponse")
	proto.RegisterType((*GetProjectRequest)(nil), "projects.GetProjectRequest")
	proto.RegisterType((*GetProjectResponse)(nil), "projects.GetProjectResponse")
	proto.RegisterType((*UpdateProjectRequest)(nil), "projects.UpdateProjectRequest")
	proto.RegisterType((*UpdateProjectResponse)(nil), "projects.UpdateProjectResponse")
	proto.RegisterType((*DeleteProjectRequest)(nil), "projects.DeleteProjectRequest")
	proto.RegisterType((*DeleteProjectResponse)(nil), "projects.DeleteProjectResponse")
	proto.RegisterType((*Project)(nil), "projects.Project")
	proto.RegisterMapType((map[string]string)(nil), "projects.Project.SecretsEntry")
	proto.RegisterType((*Repo)(nil), "projects.Repo")
	proto.RegisterType((*Kubernetes)(nil), "projects.Kubernetes")
	proto.RegisterType((*Github)(nil), "projects.Github")
	proto.RegisterType((*WorkerConfig)(nil), "projects.WorkerConfig")
}

func init() { proto.RegisterFile("projects.proto", fileDescriptor_a2826043bb82544a) }

var fileDescriptor_a2826043bb82544a = []byte{
	// 920 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0xdd, 0x34, 0x6d, 0x3e, 0x6e, 0x3f, 0x36, 0x9d, 0xcd, 0x2e, 0x56, 0x29, 0x4b, 0x64, 0x21,
	0x54, 0xf1, 0x11, 0x50, 0x01, 0xa9, 0xda, 0xb7, 0x6d, 0x8a, 0x02, 0xb4, 0xa0, 0xc8, 0xd1, 0xc2,
	0xf3, 0xc4, 0xbe, 0x75, 0x66, 0xeb, 0x78, 0xcc, 0xcc, 0xb8, 0x25, 0xfc, 0x19, 0x1e, 0x78, 0xe1,
	0x67, 0xa2, 0x19, 0x8f, 0x63, 0x3b, 0xf6, 0x0a, 0xd1, 0x7d, 0xcb, 0x9c, 0x73, 0xe6, 0xcc, 0x9d,
	0x7b, 0xef, 0xf8, 0x06, 0x8e, 0x12, 0xc1, 0xdf, 0xa2, 0xaf, 0xe4, 0x38, 0x11, 0x5c, 0x71, 0xd2,
	0xcb, 0xd7, 0xee, 0x04, 0x86, 0x13, 0x81, 0x54, 0xe1, 0x2c, 0x43, 0x3c, 0xfc, 0x3d, 0x45, 0xa9,
	0xc8, 0xe7, 0xd0, 0xb5, 0x1a, 0xa7, 0x35, 0x6a, 0x9d, 0xed, 0x9f, 0x1f, 0x8f, 0x37, 0x1e, 0xb9,
	0x34, 0x57, 0xb8, 0x57, 0xf0, 0x7c, 0xcb, 0x44, 0x26, 0x3c, 0x96, 0xf8, 0xff, 0x5c, 0x86, 0x40,
	0xa6, 0xa8, 0x2c, 0x2c, 0x6d, 0x20, 0xee, 0x15, 0x3c, 0xab, 0xa0, 0xd6, 0xf9, 0x4b, 0xd8, 0xdc,
	0xc1, 0x69, 0x8d, 0xda, 0xcd, 0xd6, 0xc5, 0x35, 0xbf, 0x83, 0xe3, 0xc2, 0x25, 0xbf, 0xe3, 0x08,
	0xf6, 0xad, 0xe0, 0x17, 0xba, 0x42, 0x13, 0x61, 0xdf, 0x2b, 0x43, 0xee, 0xeb, 0x72, 0x48, 0x8f,
	0xbb, 0xd5, 0x04, 0x86, 0x6f, 0x92, 0xe0, 0xfd, 0x13, 0xbc, 0x65, 0xf2, 0x98, 0x50, 0x2e, 0x60,
	0x78, 0x85, 0x11, 0xd6, 0x42, 0xf9, 0xef, 0x3c, 0x7c, 0x00, 0xcf, 0xb7, 0x76, 0x66, 0xe7, 0xbb,
	0x7f, 0x77, 0xa0, 0x6b, 0x31, 0x42, 0x60, 0x37, 0x2e, 0xf6, 0x9b, 0xdf, 0xc4, 0x85, 0x5d, 0x81,
	0x09, 0x77, 0x76, 0x4c, 0x70, 0x47, 0x45, 0x70, 0x1e, 0x26, 0xdc, 0x33, 0x1c, 0xf9, 0x04, 0x0e,
	0x03, 0xbc, 0xa5, 0x69, 0xa4, 0xe6, 0xbe, 0x60, 0x89, 0x72, 0xda, 0xc6, 0xa0, 0x0a, 0x92, 0x2f,
	0xe0, 0xb8, 0x02, 0x98, 0x50, 0x77, 0x8d, 0xb2, 0x4e, 0x90, 0x6f, 0x01, 0xee, 0xd2, 0x05, 0x8a,
	0x18, 0x15, 0x4a, 0x67, 0xcf, 0x9c, 0x3e, 0x2c, 0x4e, 0xbf, 0xde, 0x70, 0x5e, 0x49, 0x47, 0x5c,
	0x38, 0x90, 0x4b, 0x2a, 0x30, 0x98, 0xa3, 0x2f, 0x50, 0x39, 0x1d, 0x63, 0x5f, 0xc1, 0xc8, 0x19,
	0x74, 0x42, 0xa6, 0x96, 0xe9, 0xc2, 0xe9, 0x1a, 0xd7, 0x41, 0xe1, 0x3a, 0x35, 0xb8, 0x67, 0x79,
	0x72, 0x01, 0x5d, 0x69, 0xf6, 0x48, 0xa7, 0x67, 0x3a, 0xf4, 0x65, 0xad, 0x36, 0xe3, 0xcc, 0x54,
	0x7e, 0x1f, 0x2b, 0xb1, 0xf6, 0x72, 0x39, 0x19, 0x43, 0xe7, 0x37, 0x2e, 0xee, 0x50, 0x38, 0x7d,
	0x73, 0xc6, 0x8b, 0x62, 0x63, 0x86, 0x4f, 0x78, 0x7c, 0xcb, 0x42, 0xcf, 0xaa, 0x74, 0x6e, 0x58,
	0xcc, 0xd4, 0x94, 0xa9, 0x79, 0xba, 0x58, 0xf1, 0x20, 0x8d, 0x50, 0x3a, 0x30, 0x6a, 0x9d, 0xf5,
	0xbc, 0x3a, 0x41, 0xbe, 0x86, 0x67, 0x34, 0x8a, 0xf8, 0xc3, 0x4c, 0xb0, 0x7b, 0x16, 0x61, 0x88,
	0xc1, 0x4f, 0x7c, 0x21, 0x9d, 0x7d, 0xa3, 0x6f, 0xa2, 0xc8, 0x19, 0x3c, 0x35, 0xf0, 0x0f, 0x5c,
	0xaa, 0x9f, 0x79, 0x1a, 0x2b, 0xe9, 0x1c, 0x18, 0xf5, 0x36, 0x4c, 0x3e, 0x83, 0x01, 0x5b, 0xd1,
	0x10, 0x67, 0x69, 0x14, 0xd9, 0xbb, 0x39, 0x87, 0x26, 0x8b, 0x35, 0x5c, 0xd7, 0xfd, 0xc1, 0xde,
	0x66, 0xb5, 0xa2, 0x71, 0xe0, 0x1c, 0x65, 0x75, 0xaf, 0x80, 0x5a, 0x75, 0x29, 0x58, 0x48, 0x03,
	0x7c, 0x2b, 0x67, 0x54, 0x2d, 0x9d, 0xa7, 0x99, 0xaa, 0x02, 0xea, 0x0c, 0x58, 0x20, 0x4b, 0x8d,
	0x51, 0x0e, 0xb2, 0xee, 0xa8, 0x11, 0xe4, 0x1c, 0x86, 0x53, 0x8c, 0x51, 0x30, 0x7f, 0x4a, 0x15,
	0x3e, 0xd0, 0xb5, 0xad, 0xf7, 0xb1, 0xd9, 0xd0, 0xc8, 0x9d, 0xbc, 0x82, 0x83, 0x72, 0xb1, 0xc8,
	0x00, 0xda, 0x77, 0xb8, 0xb6, 0xcd, 0xae, 0x7f, 0x92, 0x21, 0xec, 0xdd, 0xd3, 0x28, 0x45, 0xd3,
	0xec, 0x7d, 0x2f, 0x5b, 0xbc, 0xda, 0xb9, 0x68, 0xb9, 0x4b, 0xd8, 0xd5, 0xfd, 0xde, 0xf8, 0x42,
	0x4e, 0xa0, 0xe7, 0x47, 0x3c, 0xc6, 0x37, 0xde, 0x8d, 0xdd, 0xb8, 0x59, 0x93, 0x17, 0xd0, 0x91,
	0x72, 0x79, 0x8d, 0x6b, 0xfb, 0x24, 0xec, 0x8a, 0x38, 0xd0, 0x95, 0x72, 0x39, 0x41, 0xa1, 0xec,
	0x0b, 0xc8, 0x97, 0xee, 0x3f, 0x3b, 0x00, 0x45, 0x73, 0x93, 0x53, 0xe8, 0xeb, 0x43, 0x64, 0x42,
	0xfd, 0xfc, 0xd4, 0x02, 0x20, 0x2f, 0x01, 0xee, 0x7d, 0x39, 0x67, 0x01, 0xfa, 0x54, 0xd8, 0xc3,
	0x4b, 0x88, 0x2e, 0xe6, 0x22, 0x65, 0x51, 0x30, 0x57, 0x5c, 0xd0, 0x10, 0xe7, 0xec, 0x4f, 0xb4,
	0x81, 0xd4, 0x70, 0x5d, 0x80, 0x32, 0x36, 0x89, 0xa8, 0x94, 0xf9, 0xf3, 0xac, 0x11, 0x5a, 0xed,
	0x53, 0x7f, 0x89, 0x15, 0xf5, 0x5e, 0xa6, 0xae, 0x11, 0x5a, 0x6d, 0xfa, 0x2c, 0xcb, 0xff, 0x35,
	0xae, 0x3d, 0xbc, 0x35, 0x6f, 0xb3, 0xe7, 0xd5, 0x09, 0xf2, 0x29, 0x1c, 0x49, 0x14, 0xf7, 0xcc,
	0xc7, 0xd7, 0xbe, 0xaf, 0xbb, 0xd2, 0x3c, 0xd4, 0xbe, 0xb7, 0x85, 0xba, 0xbf, 0x42, 0x27, 0x7b,
	0xb0, 0xba, 0x70, 0x8a, 0xdf, 0x61, 0x6c, 0x33, 0x94, 0x2d, 0x74, 0x92, 0x17, 0x54, 0x96, 0xea,
	0x92, 0x2f, 0x75, 0x56, 0xd3, 0x24, 0xe2, 0x34, 0xd0, 0x5c, 0x96, 0x90, 0x02, 0x70, 0x13, 0x38,
	0x28, 0x3f, 0x52, 0x5d, 0x60, 0x81, 0x21, 0x93, 0x4a, 0xe4, 0xdd, 0xb2, 0x59, 0x6f, 0x1a, 0x62,
	0xa7, 0xd4, 0x10, 0x03, 0x68, 0x2b, 0x1a, 0x5a, 0x5f, 0xfd, 0x53, 0xd7, 0x29, 0x49, 0xa3, 0x68,
	0xc6, 0x23, 0xe6, 0xaf, 0x6d, 0x52, 0x4b, 0xc8, 0xf9, 0x5f, 0x6d, 0xe8, 0xe5, 0x03, 0x92, 0x78,
	0x70, 0x58, 0x99, 0xc5, 0xa4, 0xf4, 0xd5, 0x69, 0x9a, 0xf4, 0x27, 0x1f, 0xbf, 0x93, 0xb7, 0xdf,
	0xf8, 0x27, 0xe4, 0x06, 0xf6, 0x4b, 0x33, 0x98, 0x9c, 0x96, 0x3e, 0x79, 0xb5, 0x81, 0x7d, 0xf2,
	0xd1, 0x3b, 0xd8, 0x8d, 0xdb, 0x8f, 0x00, 0x05, 0x41, 0x3e, 0x6c, 0x92, 0xe7, 0x5e, 0xa7, 0xcd,
	0xe4, 0xc6, 0xca, 0x83, 0xc3, 0xca, 0x5c, 0x2c, 0x5f, 0xb6, 0x69, 0xea, 0x96, 0x2f, 0xdb, 0x38,
	0x50, 0x33, 0xcf, 0xca, 0xac, 0x2b, 0x7b, 0x36, 0x8d, 0xcf, 0xb2, 0x67, 0xf3, 0x90, 0x7c, 0x72,
	0xf9, 0x15, 0x8c, 0x18, 0x1f, 0x07, 0xc8, 0x64, 0x44, 0x17, 0x72, 0xcc, 0x25, 0x13, 0x4c, 0x8e,
	0xf1, 0x0f, 0xba, 0x4a, 0x22, 0x94, 0xe3, 0x88, 0x87, 0xf2, 0xb2, 0x7f, 0xc3, 0x43, 0x39, 0xd3,
	0x7f, 0xcf, 0x66, 0xad, 0x45, 0xc7, 0xfc, 0x4f, 0xfb, 0xe6, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdb, 0x17, 0x6f, 0x3a, 0xb9, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectsClient is the client API for Projects service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectsClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error)
}

type projectsClient struct {
	cc *grpc.ClientConn
}

func NewProjectsClient(cc *grpc.ClientConn) ProjectsClient {
	return &projectsClient{cc}
}

func (c *projectsClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/projects.Projects/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, "/projects.Projects/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error) {
	out := new(GetProjectResponse)
	err := c.cc.Invoke(ctx, "/projects.Projects/GetProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error) {
	out := new(UpdateProjectResponse)
	err := c.cc.Invoke(ctx, "/projects.Projects/UpdateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error) {
	out := new(DeleteProjectResponse)
	err := c.cc.Invoke(ctx, "/projects.Projects/DeleteProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectsServer is the server API for Projects service.
type ProjectsServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*UpdateProjectResponse, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error)
}

func RegisterProjectsServer(s *grpc.Server, srv ProjectsServer) {
	s.RegisterService(&_Projects_serviceDesc, srv)
}

func _Projects_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/UpdateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/DeleteProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Projects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projects.Projects",
	HandlerType: (*ProjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _Projects_CreateProject_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _Projects_GetProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _Projects_GetProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _Projects_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _Projects_DeleteProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "projects.proto",
}
