apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brigade.apiserver.fullname" . }}
  labels:
    {{- include "brigade.labels" . | nindent 4 }}
    {{- include "brigade.apiserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.apiserver.rootUser.enabled }}
  root-user-password: {{ .Values.apiserver.rootUser.password }}
  {{- end }}
  {{- if .Values.apiserver.oidc.enabled }}
  oidc-client-secret: {{ .Values.apiserver.oidc.clientSecret }}
  {{- end }}
  {{- if not .Values.mongodb.enabled }}
  mongodb-connection-string: {{ .Values.externalMongodb.connectionString }}
  {{- end }}
  {{- if eq .Values.messageBus "IncludedArtemis" }}
  amqp-password: {{ .Values.artemis.password }}
  {{- else if eq .Values.messageBus "ExternalAMQP" }}
  amqp-password: {{ .Values.externalAMQP.password }}
  {{- else if eq .Values.messageBus "AzureServiceBus" }}
  amqp-password: {{ .Values.azureServiceBus.password }}
  {{- end }}
