apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brignext.apiserver.fullname" . }}
  labels:
    {{- include "brignext.labels" . | nindent 4 }}
    {{- include "brignext.apiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiserver.replicas }}
  selector:
    matchLabels:
      {{- include "brignext.selectorLabels" . | nindent 6 }}
      {{- include "brignext.apiserver.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "brignext.selectorLabels" . | nindent 8 }}
        {{- include "brignext.apiserver.labels" . | nindent 8 }}
      annotations:
        checksum/apiserver-secret: {{ include (print $.Template.BasePath "/apiserver/secret.yaml") . | sha256sum }}
        checksum/scheduler-secret: {{ include (print $.Template.BasePath "/scheduler/secret.yaml") . | sha256sum }}
        checksum/observer-secret: {{ include (print $.Template.BasePath "/observer/secret.yaml") . | sha256sum }}
        {{- if .Values.apiserver.tls.enabled }}
        checksum/cert-secret: {{ include (print $.Template.BasePath "/apiserver/cert-secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      serviceAccount: {{ include "brignext.apiserver.fullname" . }}
      containers:
      - name: apiserver
        image: {{ .Values.apiserver.image.repository }}:{{ default .Chart.AppVersion .Values.apiserver.image.tag }}
        imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
        args:
        - --logtostderr=true
        env:
        - name: API_SERVER_ROOT_USER_ENABLED
          value: {{ quote .Values.apiserver.rootUser.enabled }}
        {{- if .Values.apiserver.rootUser.enabled }}
        - name: API_SERVER_ROOT_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "brignext.apiserver.fullname" . }}
              key: root-user-password
        {{- end }}
        - name: API_SERVER_SCHEDULER_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "brignext.scheduler.fullname" . }}
              key: api-token
        - name: API_SERVER_OBSERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "brignext.observer.fullname" . }}
              key: api-token
        - name: OIDC_ENABLED
          value: {{ quote .Values.apiserver.oidc.enabled }}
        {{- if .Values.apiserver.oidc.enabled }}
        - name: OIDC_PROVIDER_URL
          value: {{ .Values.apiserver.oidc.providerURL }}
        - name: OIDC_CLIENT_ID
          value: {{ .Values.apiserver.oidc.clientID }}
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "brignext.apiserver.fullname" . }}
              key: oidc-client-secret
        - name: OIDC_REDIRECT_URL_BASE
          {{- if or (and (not .Values.apiserver.ingress.enabled) .Values.apiserver.tls.enabled) (and .Values.apiserver.ingress.enabled .Values.apiserver.ingress.tls.enabled) }}
          value: https://{{ .Values.apiserver.host }}
          {{- else }}
          value: http://{{ .Values.apiserver.host }}
          {{- end }}
        {{- end }}
        - name: API_SERVER_TLS_ENABLED
          value: {{ quote .Values.apiserver.tls.enabled }}
        {{- if .Values.apiserver.tls.enabled }}
        - name: API_SERVER_TLS_CERT_PATH
          value: /app/certs/tls.crt
        - name: API_SERVER_TLS_KEY_PATH
          value: /app/certs/tls.key
        {{- end }}
        {{- if .Values.mongodb.enabled }}
        - name: MONGODB_HOST
          value: {{ include "call-nested" (list . "mongodb" "mongodb.fullname") }}.{{ .Release.Namespace }}.svc.cluster.local
        - name: MONGODB_PORT
          value: {{ quote .Values.mongodb.service.port }}
        - name: MONGODB_DATABASE
          value: {{ .Values.mongodb.mongodbDatabase }}
        - name: MONGODB_REPLICA_SET
          value: {{ .Values.mongodb.replicaSet.name }}
        - name: MONGODB_USERNAME
          value: {{ .Values.mongodb.mongodbUsername }}
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "call-nested" (list . "mongodb" "mongodb.fullname") }}
              key: mongodb-password
        {{- else }}
        - name: MONGODB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ include "brignext.apiserver.fullname" . }}
              key: mongodb-connection-string
        - name: MONGODB_DATABASE
          value: {{ .Values.externalMongodb.database }}
        {{- end }}
        {{- if eq .Values.messageBus "IncludedArtemis" }}
        - name: AMQP_ADDRESS
          value: amqp://{{ include "brignext.artemis.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5672
        - name: AMQP_USERNAME
          value: {{ .Values.artemis.username }}
        {{- else if eq .Values.messageBus "ExternalAMQP" }}
        - name: AMQP_ADDRESS
          value: {{ .Values.externalAMQP.address }}
        - name: AMQP_USERNAME
          value: {{ .Values.externalAMQP.username }}
        {{- else if eq .Values.messageBus "AzureServiceBus" }}
        - name: AMQP_ADDRESS
          value: {{ .Values.azureServiceBus.address }}
        - name: AMQP_USERNAME
          value: {{ .Values.azureServiceBus.username }}
        - name: AMQP_IS_AZURE_SERVICE_BUS
          value: "true"
        {{- end }}
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "brignext.apiserver.fullname" . }}
              key: amqp-password
        - name: DEFAULT_WORKER_IMAGE
          value: {{ .Values.worker.image.repository }}:{{ default .Chart.AppVersion .Values.worker.image.tag }}
        - name: DEFAULT_WORKER_IMAGE_PULL_POLICY
          value: {{ .Values.worker.image.pullPolicy }}
        - name: WORKSPACE_STORAGE_CLASS
          value: {{ .Values.worker.workspaceStorageClass }}
        {{- if .Values.apiserver.tls.enabled }}
        volumeMounts:
        - name: cert
          mountPath: /app/certs
          readOnly: true
        {{- end }}
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthz
            {{- if .Values.apiserver.tls.enabled }}
            scheme: HTTPS
            {{- else }}
            scheme: HTTP
            {{- end }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
            path: /healthz
            {{- if .Values.apiserver.tls.enabled }}
            scheme: HTTPS
            {{- else }}
            scheme: HTTP
            {{- end }}
          initialDelaySeconds: 15
          periodSeconds: 20
      {{- if .Values.apiserver.tls.enabled }}
      volumes:
      - name: cert
        secret:
          secretName: {{ include "brignext.apiserver.fullname" . }}-cert
      {{- end }}
      {{- with .Values.apiserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
