apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brignext.apiserver.fullname" . }}
  labels:
    {{- include "brignext.labels" . | nindent 4 }}
    {{- include "brignext.apiserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.apiserver.rootUser.enabled }}
  root-user-password: {{ .Values.apiserver.rootUser.password }}
  {{- end }}
  {{- if .Values.apiserver.oidc.enabled }}
  oidc-client-secret: {{ .Values.apiserver.oidc.clientSecret }}
  {{- end }}
  {{- if not .Values.mongodb.enabled }}
  mongodb-connection-string: {{ .Values.externalMongodb.connectionString }}
  {{- end }}
