apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brignext.apiserver.fullname" . }}
  labels:
    {{- include "brignext.labels" . | nindent 4 }}
    {{- include "brignext.apiserver.labels" . | nindent 4 }}
stringData:
  oidc-client-secret: {{ .Values.apiserver.oidc.clientSecret }}
