apiVersion: v1
kind: Service
metadata:
  name: {{ include "brignext.apiserver.fullname" . }}
  labels:
    {{- include "brignext.labels" . | nindent 4 }}
    {{- include "brignext.apiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    {{- if .Values.apiserver.tls.enabled }}
    - port: 443
    {{- else }}
    - port: 80
    {{- end }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "brignext.selectorLabels" . | nindent 8 }}
    {{- include "brignext.apiserver.labels" . | nindent 8 }}
