apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brignext.fluentd.fullname" . }}
  labels:
    {{- include "brignext.labels" . | nindent 4 }}
    {{- include "brignext.fluentd.labels" . | nindent 4 }}
stringData:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/brignext-fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S
      tag kube.*
      format json
      read_from_head true
      refresh_interval 15
    </source>

    <filter kube.var.log.containers.**.log>
      @type kubernetes_metadata
    </filter>

    <match kube.var.log.containers.**.log>
      @type rewrite_tag_filter
      <rule>
        key     $.kubernetes.labels.component
        pattern /^build$/
        tag     build
      </rule>
      <rule>
        key     $.kubernetes.labels.component
        pattern /^job$/
        tag     job
      </rule>
    </match>

    <match build>
      @type rewrite_tag_filter
      <rule>
        key     $.kubernetes.labels.build
        pattern /^(.*)$/
        tag     build.$1
      </rule>
    </match>

    <match job>
      @type rewrite_tag_filter
      <rule>
        key     $.kubernetes.pod_name
        pattern /^(.*)$/
        tag     job.$1
      </rule>
    </match>

    <match build.* job.*>
      @type rewrite_tag_filter
      <rule>
        key     $.kubernetes.container_name
        pattern /^(.*)$/
        tag     ${tag}.$1
      </rule>
    </match>

    <filter build.** job.**>
      @type        record_transformer
      renew_record true
      keep_keys    time,log
    </filter>

    <match build.** job.**>
      @type mongo
      host {{ include "call-nested" (list . "mongodb" "mongodb.fullname") }}.{{ .Release.Namespace }}.svc.cluster.local
      port 27017
      database {{ .Values.mongodb.mongodbDatabase }}

      user {{ .Values.mongodb.mongodbUsername }}
      password {{ .Values.mongodb.mongodbPassword }}

      collection ${tag}
      capped
      capped_size 64m
      time_key time

      <buffer>
        @type          file
        path           /fluentd/log/buffer
        flush_interval 5s
      </buffer>
    </match>
