apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brignext.fluentd.fullname" . }}
  labels:
    {{- include "brignext.labels" . | nindent 4 }}
    {{- include "brignext.fluentd.labels" . | nindent 4 }}
stringData:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/brignext-fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S
      tag kube.*
      format json
      read_from_head true
      refresh_interval 15
    </source>

    <filter kube.var.log.containers.**.log>
      @type kubernetes_metadata
    </filter>

    <match kube.var.log.containers.**.log>
      @type rewrite_tag_filter
      <rule>
        key     $.kubernetes.labels.brignext_io/component
        pattern /^worker$/
        tag     worker
      </rule>
      <rule>
        key     $.kubernetes.labels.brignext_io/component
        pattern /^job$/
        tag     job
      </rule>
    </match>

    <filter worker>
      @type record_transformer
      enable_ruby
      renew_record true
      <record>
        component ${record.dig("kubernetes", "labels", "brignext_io/component")}
        event     ${record.dig("kubernetes", "labels", "brignext_io/event")}
        worker    ${record.dig("kubernetes", "labels", "brignext_io/worker")}
        container ${record.dig("kubernetes", "container_name")}
      </record>
      keep_keys component,event,worker,container,time,log
    </filter>

    <filter job>
      @type record_transformer
      enable_ruby
      renew_record true
      <record>
        component ${record.dig("kubernetes", "labels", "brignext_io/component")}
        event     ${record.dig("kubernetes", "labels", "brignext_io/event")}
        worker    ${record.dig("kubernetes", "labels", "brignext_io/worker")}
        job       ${record.dig("kubernetes", "labels", "brignext_io/job")}
        container ${record.dig("kubernetes", "container_name")}
      </record>
      keep_keys component,event,worker,job,container,time,log
    </filter>

    <match worker job>
      @type mongo
      host {{ include "call-nested" (list . "mongodb" "mongodb.fullname") }}.{{ .Release.Namespace }}.svc.cluster.local
      port 27017
      database {{ .Values.mongodb.mongodbDatabase }}

      user {{ .Values.mongodb.mongodbUsername }}
      password {{ .Values.mongodb.mongodbPassword }}

      collection logs
      capped
      capped_size 64m
      time_key time

      <buffer>
        @type file
        path /fluentd/log/buffer
        flush_interval 5s
      </buffer>
    </match>
