package main

const (
	flagBackground  = "background"
	flagsBackground = "background, b"
	flagCommit      = "commit"
	flagsCommit     = "commit, c"
	flagConfig      = "config"
	flagContainer   = "container"
	flagsContainer  = "container, c"
	flagEvent       = "event"
	flagsEvent      = "event, e"
	flagFile        = "file"
	flagsFile       = "file, f"
	flagForce       = "force"
	flagsForce      = "force, f"
	flagInit        = "init"
	flagsInit       = "init, i"
	flagJobs        = "jobs"
	flagsJobs       = "jobs, j"
	flagLast        = "last"
	flagsLast       = "last, l"
	flagLevel       = "level"
	flagsLevel      = "level, l"
	flagOutput      = "output"
	flagsOutput     = "output, o"
	flagPayload     = "payload"
	flagsPayload    = "payload, p"
	flagPassword    = "password"
	flagsPassword   = "password, p"
	flagRef         = "ref"
	flagsRef        = "ref, r"
	flagUsername    = "username"
	flagsUsername   = "username, u"
)
