package main

const (
	flagBrowse       = "browse"
	flagsBrowse      = "browse, b"
	flagDescription  = "description"
	flagsDescription = "description, d"
	flagForce        = "force"
	flagsForce       = "force, f"
	flagInit         = "init"
	flagInsecure     = "insecure"
	flagsInsecure    = "insecure, k"
	flagOutput       = "output"
	flagsOutput      = "output, o"
	flagPassword     = "password"
	flagsPassword    = "password, p"
	flagProject      = "project"
	flagsProject     = "project, p"
	flagProvider     = "provider"
	flagsProvider    = "provider, p"
	flagRoot         = "root"
	flagsRoot        = "root, r"
	flagType         = "type"
	flagsType        = "type, t"
)
