apiVersion: github.com/krancour/brignext/v2
kind: Project
metadata:
  id: hello-world
description: The simplest possible demonstration
spec:
  worker:
    defaultConfigFiles:
      brignext.js: |-
        const { events } = require("brigadier");

        events.on("github.com/krancour/brignext/cli:exec", (e) => {
          console.log("Hello, World!");
        });
