apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: hello-world
description: The simplest possible demonstration
spec:
  workerTemplate:
    defaultConfigFiles:
      brigade.js: |-
        const { events } = require("brigadier");

        events.on("github.com/brigadecore/brigade/cli:exec", (e) => {
          console.log("Hello, World!");
        });
