apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: logs-demo
description: A project that demonstrates outputting logs from a job
spec:
  workerTemplate:
    defaultConfigFiles:
      brigade.js: |-
        const { events, Job } = require("brigadier");

        events.on("github.com/brigadecore/brigade/cli:exec", (e) => {
          let job = new Job("foo", "debian:latest");
          job.primaryContainer.command = ["echo"];
          job.primaryContainer.arguments = ["foo"];
          job.run()
          .then(result => {
            console.log(result.toString());
            console.log("done");
          }).catch(e => {
            console.error(e);
          });
        });
