apiVersion: github.com/krancour/brignext/v2
kind: Project
metadata:
  id: pipeline-demo
description: A project that demonstrates a simple pipeline
spec:
  workerTemplate:
    defaultConfigFiles:
      brignext.js: |-
        const { events, Job } = require("brigadier");

        events.on("github.com/krancour/brignext/cli:exec", (e) => {
          let fooJob = new Job("foo", "debian:latest");
          fooJob.primaryContainer.command = ["echo"];
          fooJob.primaryContainer.arguments = ["foo"];
          fooJob.run()
          .then(() => {
            let barJob = new Job("bar", "debian:latest");
            barJob.primaryContainer.command = ["echo"];
            barJob.primaryContainer.arguments = ["bar"];
            return barJob.run();
          })
          .then(() => {
            console.log("done");
          }).catch(e => {
            console.error(e);
          });
        });
