apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: secrets-demo
description: A project that demonstrates the use of secrets
spec:
  workerTemplate:
    defaultConfigFiles:
      brigade.js: |-
        const { events, Job, Group, Container} = require("brigadier");

        events.on("github.com/brigadecore/brigade/cli:exec", (e) => {
          let job = new Job("foo", "debian:latest");
          job.primaryContainer.command = ["echo"];
          job.primaryContainer.arguments = ["foo"];
          job.primaryContainer.environment = {
            "FOO": e.project.secrets.foo
          };
          
          job.run()
          .then(() => {
            console.log("done");
          }).catch(e => {
            console.error(e);
          });
        });
