apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: github-demo
description: A project that demonstrates integration with GitHub
spec:
  eventSubscriptions:
  - source: github.com/brigadecore/brigade-github-app
    types:
    - pull_request:opened
    - pull_request:synchronize
    - pull_request:reopened
    - push
    labels:
      repo: krancour/brignext-demo
  workerTemplate:
    git:
      cloneURL: https://github.com/brigadecore/brigade-demo.git
