apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: npm-dependencies-demo
description: A project that demonstrates installing pre-requisite npm packages
spec:
  workerTemplate:
    defaultConfigFiles:
      brigade.json: |-
        {
          "dependencies": {
              "unique-names-generator": "4.0.0"
          }
        }
      brigade.js: |-
        const { events } = require("brigadier");
        const { uniqueNamesGenerator, adjectives, animals } = require("unique-names-generator");

        randomName = uniqueNamesGenerator({
          dictionaries: [adjectives, animals],
          length: 2,
          separator: '-'
        });

        events.on("github.com/brigadecore/brigade/cli:exec", (e) => {
          console.log(`Hello, ${randomName}!`);
        });
