apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: sidecar-demo
description: A project that demonstrates a job that uses a sidecar container
spec:
  workerTemplate:
    defaultConfigFiles:
      brigade.js: |-
        const { events, Job, Group, Container} = require("brigadier");

        events.on("github.com/brigadecore/brigade/cli:exec", (e) => {
          let job = new Job("foo", "debian:latest");
          job.primaryContainer.command = ["echo"];
          job.primaryContainer.arguments = ["foo"];

          job.sidecarContainers.sleeper = new Container("debian:latest");
          job.sidecarContainers.sleeper.command = ["sleep"];
          job.sidecarContainers.sleeper.arguments = ["1000"];

          job.run()
          .then(() => {
            console.log("done");
          }).catch(e => {
            console.error(e);
          });
        });
